### PR TITLE
Support for remote resource streams

### PR DESCRIPTION
**Pull request by leftdevel**
This change is [Reviewable](https://reviewable.io/reviews/leftdevel/zipstream-php/1)

### CODE REVIEW

**Comment by apinstein** [comment]
reopen

**Comment by apinstein** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

_[.gitignore, line 3 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYp1HzmIjaLQBOVrME:-KNYp1HzmIjaLQBOVrMF:-1624871367) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/.gitignore#L3)):_

> ```
> vendor/
> clover.xml
> phpunit.xml
> ```

why adding an ignore for this? did you custom-make a phpunit.xml for this project for testing something yourself? seems weird to ignore a file that would normally be included in a repo...

---

_[src/ZipStream.php, line 244 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYpFhUjYRbksQBVQCm:-KNYpFhUjYRbksQBVQCn:2049652049) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L244)):_

> ``` PHP
> 
>       // send file header
>       $cdr_len = $this->addFileHeader($name, $opt, $meth, $crc, $zlen, $len);
> ```

IIRC this isn't `$cdr_len` it's the length of this entry in the zip stream so the CDR knows at which offset this entry starts in the zip file? 

if so, this name should be fixed... maybe `$offsetInArchive`?

---

_[src/ZipStream.php, line 245 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYpUxFTxVqR96vU8Nz:-KNYpUxFTxVqR96vU8O-:435545447) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L245)):_

> ``` PHP
>       // send file header
>       $cdr_len = $this->addFileHeader($name, $opt, $meth, $crc, $zlen, $len);
>       $this->addToCdr($name, $opt, $meth, $crc, $zlen, $len, $cdr_len);
> ```

this is you pulling out the responsibility to add the CDR entry into each `addXXX` function, right? I do agree this seems better than the `$addCdrEntry` boolean flag. 

Nice.

---

_[src/ZipStream.php, line 335 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYpw-MmiO_QuaNJpDA:-KNYpw-MmiO_QuaNJpDB:-961570739) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L335)):_

> ``` PHP
>       $block_size = 1048576; // process in 1 megabyte chunks
>       $algo       = 'crc32b';
>       $meth       = 0x00;
> ```

i know these magic strings aren't yours, but they deserve better docs :)

---

_[src/ZipStream.php, line 337 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYphelxIQ4Qvd0jY_D:-KNYphelxIQ4Qvd0jY_E:-685673390) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L337)):_

> ``` PHP
>       $meth       = 0x00;
>       // General bit flag. For remote resources, we don't know the content size nor the crc until the full data has been sent.
>       $genb       = 0x08;
> ```

this should be defined as  a CONSTANT and I'd prolly include a URL to the description  of the documentation.

---

_[src/ZipStream.php, line 338 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYqlgvdNCmQIZHDFJJ:-KNYqlgvdNCmQIZHDFJK:-1343830639) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L338)):_

> ``` PHP
>       // General bit flag. For remote resources, we don't know the content size nor the crc until the full data has been sent.
>       $genb       = 0x08;
>       $zlen       = $len = $crc = 0;
> ```

do you think these might be more self-explanatory as flags? like

```
const VALUE_DEFERRED_TO_DATA_DESCRIPTOR = 0;
```

---

_[src/ZipStream.php, line 339 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYrkacOekqAHhSHfdO:-KNYrkacOekqAHhSHfdP:-566072483) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L339)):_

> ``` PHP
>       $genb       = 0x08;
>       $zlen       = $len = $crc = 0;
>       $hash_ctx   = hash_init($algo);
> ```

since this func now interleaves multiple things (passing along data, incrementally calculating crc32), i'd comment these things more clearly. it's hard to tell from the way the code is presently laid out, which LOC in this func are about crc and which are about streaming the data.

---

_[src/ZipStream.php, line 342 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYsM4kCXDCGW5VwZW-:-KNYsM4kCXDCGW5VwZW0:-1324301168) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L342)):_

> ``` PHP
> 
>       // send local file header.
>       $initial_cdr_len = $this->addFileHeader($name, $opt, $meth, $crc, $zlen, $len, $genb);
> ```

again, `$initial_cdr_len`this isn't actually the cdr len, but instead the OFFSET to the beginning of this file in the archive? or the length of this particular entry?

a more canonical way to handle this prob is

```
$zipFileEntryTotalRecordLength = 0;
$zipFileEntryTotalRecordLength += $this->addFileHeader(...);
$zipFileEntryTotalRecordLength += $dataDescriptorLength;
...
$this->addCdr(..., $zipFileEntryTotalRecordLength);
```

---

_[src/ZipStream.php, line 348 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYrVxPACBgvRonlTmy:-KNYrVxPACBgvRonlTmz:-192304472) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L348)):_

> ``` PHP
>           hash_update($hash_ctx, $data);
>           // $zlen and $len are the same since we don't use deflate atm.
>           $zlen = $len += strlen($data);
> ```

this is goofy. I have no idea how to reason about its correctness without trying it...

just split to two lines for better readability.

---

_[src/ZipStream.php, line 362 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYsv0ilAXUjbnLW3lA:-KNYsv0ilAXUjbnLW3lB:569624784) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L362)):_

> ``` PHP
>       $rec_leng      =  $final_cdr_len + $dd_len;
>       // add to central directory record and increment offset
>       $this->addToCdr($name, $opt, $meth, $crc, $zlen, $len, $rec_leng);
> ```

actually, does the entry in the "added file" data not have enough information to calcualte `rec_leng` internally?

---

_[src/ZipStream.php, line 369 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYt4_S7Rv1czsMT-kP:-KNYt4_Trg5z99GF0xXU:1802474058) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L369)):_

> ``` PHP
>    * @param Integer  $zlen
>    * @param String   $crc
>    * @return Integer $ret_len
> ```

link to wikipedia docs for this format

https://en.wikipedia.org/wiki/Zip_(file_format)#File_headers "see Data Descriptor"

---

_[src/ZipStream.php, line 419 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYtIgaOWTEtQ-AhjUS:-KNYtIgaOWTEtQ-AhjUT:-14593469) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L419)):_

> ``` PHP
>    * @return Integer $cdr_len
>    */
>   protected function addFileHeader($name, &$opt, $meth, $crc, $zlen, $len, $genb = 0x00) {
> ```

you need a constant for `GENERAL_PURPOSE_BIT_FLAG_NONE = 0x0000` and remember it's 2 bytes!!!

Is there a reason that opts isn't where this should go? I cannot remember if OPTS is global or local to file...

---

_[src/ZipStream.php, line 489 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYttFNIbbUBei-gyWp:-KNYttFNIbbUBei-gyWq:281493582) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L489)):_

> ``` PHP
>       // pack fields and calculate "total" length
>       $ret     = $this->packFields($fields);
>       $header  = $ret . $name;
> ```

what header is this? the "Local File Header"? If so let's use better var name.

---

_[src/ZipStream.php, line 490 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYu-hCrhXEoBMSBrHc:-KNYu-hCrhXEoBMSBrHd:-789712773) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L490)):_

> ``` PHP
>       $ret     = $this->packFields($fields);
>       $header  = $ret . $name;
>       $cdr_len = strlen($header) + $zlen;
> ```

again this isn't actually cdr_len, right? it's the total size of the "File Entry"?

---

_[src/ZipStream.php, line 554 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYu73H8jyVh5HvJ2gs:-KNYu73H8jyVh5HvJ2gt:871842793) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L554)):_

> ``` PHP
> 
>       // send file header
>       $cdr_len = $this->addFileHeader($name, $opt, $meth, $crc, $zlen, $len);
> ```

var name

---

_[test/ZipStreamTest.php, line 162 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYuC1hW6kLPBbNeVu7:-KNYuC1iS6il9zd3ZifW:604308855) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/test/ZipStreamTest.php#L162)):_

> ``` PHP
>       $streamExample = fopen('php://temp', 'w+');
>       fwrite($streamExample, "Sample String Data");
>       fseek($streamExample, SEEK_SET, 0); // rewind to the start, otherwise there will be no content.
> ```

you had to fix 2 tests? did you add any tests?

maybe since what you implemented was essentially making `addFileFromStream()` not ever SEEK, you could write a test using a filesystem resource that doesn't allow seeking? I am not sure that's really easy, don't see a way to do that. just thinking about how to test that what you did actually works...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1)_

**Comment by apinstein** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

_[src/ZipStream.php, line 149 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYxovWnoOKH7Q2xxFH:-KNYxovWnoOKH7Q2xxFI:393773253) ([raw file](https://github.com/leftdevel/zipstream-php/blob/c492ddf4abcb0f6bed287faae35ebe77be7b690f/src/ZipStream.php#L149)):_

> ``` PHP
>    * not sending HTTP headers.
>    *
>    * Large File Support:
> ```

should you refactor all of this shit, too? so that these "utility" functions just pass thru to your functions?

one thing I know you haven't supported yet is DEFLATE on the stream. which we don't use, but should be pretty easily to implement?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1)_

**Comment by leftdevel** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

_[.gitignore, line 3 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYp1HzmIjaLQBOVrME:-KNYxG15ukgP73fII71H:1145820168) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/.gitignore#L3)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> why adding an ignore for this? did you custom-make a phpunit.xml for this project for testing something yourself? seems weird to ignore a file that would normally be included in a repo...
> </details>
> There is a phpunit.xml.dist in this repo. So I thought it would be a common task to have a phpunit.xml at hand. I can revert this commit if you think it only adds noise.

---

_[src/ZipStream.php, line 149 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYxovWnoOKH7Q2xxFH:-KNYyOYlhmaUjfgtr3eb:-2076167241) ([raw file](https://github.com/leftdevel/zipstream-php/blob/c492ddf4abcb0f6bed287faae35ebe77be7b690f/src/ZipStream.php#L149)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> should you refactor all of this shit, too? so that these "utility" functions just pass thru to your functions?
> 
> one thing I know you haven't supported yet is DEFLATE on the stream. which we don't use, but should be pretty easily to implement?
> </details>
> Might be yes. But as you mentioned, I just did the min viable changes, without affecting the behavior of existing methods that much. I would love to refactor the whole lib : ) But that particular method is using some crazy filtering:

```
    $filter = stream_filter_append($fh, 'zlib.deflate', STREAM_FILTER_READ, 6);
    while (!feof($fh)) {
        $data = fread($fh, self::BLOCK_SIZE);
        $zlen += strlen($data);
    }
    stream_filter_remove($filter);
```

I'll need to investigate how that works.

---

_[src/ZipStream.php, line 244 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYpFhUjYRbksQBVQCm:-KNYxbnCo6tpQWkm3XbN:-706584908) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L244)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> IIRC this isn't `$cdr_len` it's the length of this entry in the zip stream so the CDR knows at which offset this entry starts in the zip file? 
> 
> if so, this name should be fixed... maybe `$offsetInArchive`?
> </details>
> I kept that name since that's how it was named originally when it was calculated inside the addFileHeader method. Further more, it's not actually the offset in the archive, it's the length of the record. Thought  it is*\* the offset, but of the next file (once it's added). So I think naming it $offsetInArchive is confusing. Thoughts?

Eg: 

$offset = 0;
$file1 -> file starts at offset 0; length = 100; $offset += length;
$file 2 -> file starts at offset 100; length = 200; $offset += length;
$file 3 -> file starts at offset 300; ....etc etc.

---

_[src/ZipStream.php, line 335 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYpw-MmiO_QuaNJpDA:-KNYzQR1v6utte0TUV-G:-284725018) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L335)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> i know these magic strings aren't yours, but they deserve better docs :)
> </details>
> I'll do.

---

_[src/ZipStream.php, line 337 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYphelxIQ4Qvd0jY_D:-KNYzZGq_t8FNWnN1kTO:1689193178) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L337)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> this should be defined as  a CONSTANT and I'd prolly include a URL to the description  of the documentation.
> </details>
> Sounds good.

---

_[src/ZipStream.php, line 338 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYqlgvdNCmQIZHDFJJ:-KNYzgb68OQLdqdF8Axz:227225126) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L338)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> do you think these might be more self-explanatory as flags? like
> 
> ```
> const VALUE_DEFERRED_TO_DATA_DESCRIPTOR = 0;
> ```
> 
> </details>
> Sounds good too.

---

_[src/ZipStream.php, line 339 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYrkacOekqAHhSHfdO:-KNZ-1MiB6OIteZOO3bd:825380999) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L339)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> since this func now interleaves multiple things (passing along data, incrementally calculating crc32), i'd comment these things more clearly. it's hard to tell from the way the code is presently laid out, which LOC in this func are about crc and which are about streaming the data.
> </details>
> Sounds good.!

---

_[src/ZipStream.php, line 342 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYsM4kCXDCGW5VwZW-:-KNYzrc33kMZ9IiktETg:740067048) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L342)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> again, `$initial_cdr_len`this isn't actually the cdr len, but instead the OFFSET to the beginning of this file in the archive? or the length of this particular entry?
> 
> a more canonical way to handle this prob is
> 
> ```
> $zipFileEntryTotalRecordLength = 0;
> $zipFileEntryTotalRecordLength += $this->addFileHeader(...);
> $zipFileEntryTotalRecordLength += $dataDescriptorLength;
> ...
> $this->addCdr(..., $zipFileEntryTotalRecordLength);
> ```
> 
> </details>
> I left that name since that' show it originally was named when it was inside the addFileHeader. But I agree it's a poor naming.

---

_[src/ZipStream.php, line 348 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYrVxPACBgvRonlTmy:-KNZ-BHVxRryxbsYzQp0:1952316568) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L348)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> this is goofy. I have no idea how to reason about its correctness without trying it...
> 
> just split to two lines for better readability.
> </details>
> lol. I'll do :)

---

_[src/ZipStream.php, line 362 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYsv0ilAXUjbnLW3lA:-KNZ-GFfWBP2IZKFMRO5:-520326181) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L362)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> actually, does the entry in the "added file" data not have enough information to calcualte `rec_leng` internally?
> </details>
> I thought the same initially, but it doesn't, I'd need to add the $data descriptor length for it to calculate it, and this is the only block that makes use of the data descriptor header.

---

_[src/ZipStream.php, line 369 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYt4_S7Rv1czsMT-kP:-KNZNltqn0ovFvFJ57lW:-499146009) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L369)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> link to wikipedia docs for this format
> 
> https://en.wikipedia.org/wiki/Zip_(file_format)#File_headers "see Data Descriptor"
> </details>
> Done.

---

_[src/ZipStream.php, line 419 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYtIgaOWTEtQ-AhjUS:-KNZ-rCAytlc0ZmFZPTi:-402435974) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L419)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> you need a constant for `GENERAL_PURPOSE_BIT_FLAG_NONE = 0x0000` and remember it's 2 bytes!!!
> 
> Is there a reason that opts isn't where this should go? I cannot remember if OPTS is global or local to file...
> </details>
> That $opts is totally useless. There only use for it is to pass a 'time' (last modified date) for the given file. I was thinking to just pass a  $time = time(),  instead of $opt. But then I'd need to rework all functions that use this method.

Further more I pass a pointer reference (notice the &), because it gets updated internally, and I need that time later to be added to the CDR. But reworking it properly would take more efforts. I'll try regardless.

---

_[src/ZipStream.php, line 489 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYttFNIbbUBei-gyWp:-KNZ0K-RUf4epFaBamkm:1284844968) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L489)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> what header is this? the "Local File Header"? If so let's use better var name.
> </details>
> Yes. I'll do!

---

_[src/ZipStream.php, line 490 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYu-hCrhXEoBMSBrHc:-KNZ0h8CAd8xMyTW8_jl:991007322) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L490)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> again this isn't actually cdr_len, right? it's the total size of the "File Entry"?
> </details>
> I named it for bc reasons. That's how it was named originally (that's how they name it). I'll rename it to record_len.

---

_[test/ZipStreamTest.php, line 162 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYuC1hW6kLPBbNeVu7:-KNZ18dQJLX5_882Pciw:-2135856334) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/test/ZipStreamTest.php#L162)):_
<details><summary>

<i>Previously, apinstein (Alan Pinstein) wrote…</i></summary>



> you had to fix 2 tests? did you add any tests?
> 
> maybe since what you implemented was essentially making `addFileFromStream()` not ever SEEK, you could write a test using a filesystem resource that doesn't allow seeking? I am not sure that's really easy, don't see a way to do that. just thinking about how to test that what you did actually works...
> </details>
> I tried to find a way to see how can we programmatically tell if the resource handle (return value of fopen), can support seek(). This way I'd be able to tell if it's a local resource or remote, if local then I'd rewind it to zero and avoid hacking the test. But sadly I haven't found any references to do that. I'll look a bit more.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1)_

**Comment by apinstein** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

_[.gitignore, line 3 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYp1HzmIjaLQBOVrME:-KNZRN6L4n-czp7eZqW3:-2051700509) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/.gitignore#L3)):_
<details><summary>

<i>Previously, leftdevel (Oscar Balladares M.) wrote…</i></summary>



> There is a phpunit.xml.dist in this repo. So I thought it would be a common task to have a phpunit.xml at hand. I can revert this commit if you think it only adds noise.
> </details>
> ah -- weird. I see nothing in https://github.com/leftdevel/ZipStream-PHP/blob/master/phpunit.xml.dist that would make me think the file shouldn't just be moved to `phpunit.xml` -- any idea?

---

_[src/ZipStream.php, line 149 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYxovWnoOKH7Q2xxFH:-KNZRkSrua1GgTIeShSR:1254323097) ([raw file](https://github.com/leftdevel/zipstream-php/blob/c492ddf4abcb0f6bed287faae35ebe77be7b690f/src/ZipStream.php#L149)):_
<details><summary>

<i>Previously, leftdevel (Oscar Balladares M.) wrote…</i></summary>



> Might be yes. But as you mentioned, I just did the min viable changes, without affecting the behavior of existing methods that much. I would love to refactor the whole lib : ) But that particular method is using some crazy filtering:
> 
> ```
>     $filter = stream_filter_append($fh, 'zlib.deflate', STREAM_FILTER_READ, 6);
>     while (!feof($fh)) {
>         $data = fread($fh, self::BLOCK_SIZE);
>         $zlen += strlen($data);
>     }
>     stream_filter_remove($filter);
> ```
> 
> I'll need to investigate how that works.
> </details>
> good point; def I said keep it minimal. I think you're right to stick to that plan; might be good to ask the author if the appropriate next step for the lib would be to consolidate them internally and maybe even deprecate the hacky large file funcs.

---

_[src/ZipStream.php, line 244 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYpFhUjYRbksQBVQCm:-KNZS0RrPcT0pveEwcqu:669913834) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L244)):_
<details><summary>

<i>Previously, leftdevel (Oscar Balladares M.) wrote…</i></summary>



> I kept that name since that's how it was named originally when it was calculated inside the addFileHeader method. Further more, it's not actually the offset in the archive, it's the length of the record. Thought  it is*\* the offset, but of the next file (once it's added). So I think naming it $offsetInArchive is confusing. Thoughts?
> 
> Eg: 
> 
> $offset = 0;
> $file1 -> file starts at offset 0; length = 100; $offset += length;
> $file 2 -> file starts at offset 100; length = 200; $offset += length;
> $file 3 -> file starts at offset 300; ....etc etc.
> </details>
> oh - like it's a running offset? where is it ever persisted? if there is a set of functions that always returns BYTES WRITTEN then maybe it should just be `$headerSize` in this case, and then used as an input to calc a downstream offset?

I see your point about it being the name that _they_ used, but it's super-confusing....

---

_[src/ZipStream.php, line 419 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYtIgaOWTEtQ-AhjUS:-KNZT3XafH3bNp0PJoVN:742035052) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/src/ZipStream.php#L419)):_
<details><summary>

<i>Previously, leftdevel (Oscar Balladares M.) wrote…</i></summary>



> That $opts is totally useless. There only use for it is to pass a 'time' (last modified date) for the given file. I was thinking to just pass a  $time = time(),  instead of $opt. But then I'd need to rework all functions that use this method.
> 
> Further more I pass a pointer reference (notice the &), because it gets updated internally, and I need that time later to be added to the CDR. But reworking it properly would take more efforts. I'll try regardless.
> </details>
> eesh nevermind. i looked slightly further and `$opts` is indeed used only globally. so I wouldn't touch it. this class is a bit funky...

---

_[test/ZipStreamTest.php, line 162 [r1]](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1#-KNYuC1hW6kLPBbNeVu7:-KNZTF7VZF4-mGlippBJ:-1729045923) ([raw file](https://github.com/leftdevel/zipstream-php/blob/404f98f990e958085baf11c0978a02be4cae0d01/test/ZipStreamTest.php#L162)):_
<details><summary>

<i>Previously, leftdevel (Oscar Balladares M.) wrote…</i></summary>



> I tried to find a way to see how can we programmatically tell if the resource handle (return value of fopen), can support seek(). This way I'd be able to tell if it's a local resource or remote, if local then I'd rewind it to zero and avoid hacking the test. But sadly I haven't found any references to do that. I'll look a bit more.
> </details>
> i wonder if the better version of this would be to be able to get the OUTPUT of zipping as a string and then just assert various things in that output, like 0x08 general purpose bit, 0 for crc/len/zlen, the existence of the 12-byte header, etc. Basically, a test to assert what we verified in that hex editor... the nice thing about that is then that test is 100% isolated from the implementation and could be used for another class/refactor/etc with little effort.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/leftdevel/zipstream-php/1)_

**Pull request merged**
